spring:
  datasource:
    url: jdbc:mysql://database-h-infinite-power.cxsewiog63mk.ap-southeast-2.rds.amazonaws.com:3306/reportly?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: admin
    password: h-infinite-power
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.example.testapi: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
